// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTNT1uQwx4XFeGiEPKd5yPKlZZ7b3KFHs',
    appId: '1:726146516487:web:3b2e9e40e158abd6200ca2',
    messagingSenderId: '726146516487',
    projectId: 'free-fire-1764f',
    authDomain: 'free-fire-1764f.firebaseapp.com',
    databaseURL: 'https://free-fire-1764f.firebaseio.com',
    storageBucket: 'free-fire-1764f.appspot.com',
    measurementId: 'G-JLB2MVGN1B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcJv_CMpWQXp8SiJf1J_f2SpkmE5spq-k',
    appId: '1:726146516487:android:33c9bdfb891c1e64200ca2',
    messagingSenderId: '726146516487',
    projectId: 'free-fire-1764f',
    databaseURL: 'https://free-fire-1764f.firebaseio.com',
    storageBucket: 'free-fire-1764f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8X-MDJux68XiDZ137uxutPVNKTlWe_Oc',
    appId: '1:726146516487:ios:71c9c99c5a00219a200ca2',
    messagingSenderId: '726146516487',
    projectId: 'free-fire-1764f',
    databaseURL: 'https://free-fire-1764f.firebaseio.com',
    storageBucket: 'free-fire-1764f.appspot.com',
    iosBundleId: 'com.example.firebaseTestApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8X-MDJux68XiDZ137uxutPVNKTlWe_Oc',
    appId: '1:726146516487:ios:71c9c99c5a00219a200ca2',
    messagingSenderId: '726146516487',
    projectId: 'free-fire-1764f',
    databaseURL: 'https://free-fire-1764f.firebaseio.com',
    storageBucket: 'free-fire-1764f.appspot.com',
    iosBundleId: 'com.example.firebaseTestApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTNT1uQwx4XFeGiEPKd5yPKlZZ7b3KFHs',
    appId: '1:726146516487:web:5f454119c5398499200ca2',
    messagingSenderId: '726146516487',
    projectId: 'free-fire-1764f',
    authDomain: 'free-fire-1764f.firebaseapp.com',
    databaseURL: 'https://free-fire-1764f.firebaseio.com',
    storageBucket: 'free-fire-1764f.appspot.com',
    measurementId: 'G-NF9CLB3357',
  );
}
